name: buildDashboardPavia

on:
  schedule:
    - cron:  "*/12 * * * *"
  workflow_dispatch:
    
jobs: 
  genDashboard:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: r-lib/actions/setup-r@v2
      with:
         r-version: '4.1.2'
    - uses: r-lib/actions/setup-pandoc@v2

    - name: Cache R packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-shinydoc
        restore-keys: |
          ${{ runner.os }}-
    
    # Remove the if statement the first time you run it!
    - name: Install packages
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        install.packages(c("data.table", "httr", "jsonlite", "rvest", "flexdashboard",
        "htmlwidgets", "magrittr", "svglite", "ggplot2", "plotly", "tidyr", "DT"))
      shell: Rscript {0}
        
    - name: Run R scripts
      run: |
        source('gather_clean_data_pavia.R')
        rmarkdown::render('flexdashboard_pavia.Rmd', output_file = 'pavia.html')
      shell: Rscript {0}

    - name: Send files to cnftstats repo
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
        target_branch: main
        files: pavia.html
        remote_repository: https://github.com/cnftstats/cnftstats.github.io
        access_token: ${{ secrets.API_TOKEN_GITHUB }}
        force: true
